IMAGE_RHEL = "generic/rhel9"
N = 1

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.ssh.forward_x11 = true
    #config.timezone.value = :host

    (1..N).each do |i|
        config.vm.define "rhel9#{i}" do |rhel|
            rhel.vm.box = IMAGE_RHEL
            #rhel.vm.network "private_network", ip: "192.168.56.#{i + 30}"
            rhel.vm.hostname = "rhel9#{i}"
            rhel.vm.provider "virtualbox" do |vb|
              vb.memory = 512
              vb.cpus = 1
            end
            rhel.vm.provision "shell", inline: <<-SHELL
            sudo dnf install -y xorg-x11-xauth xorg-x11-fonts-\* xorg-x11-utils dbus-x11
            sudo dnf install -y xclock
            sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
            sudo sed -i 's/#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config
            sudo systemctl restart sshd
            sudo subscription-manager register --auto-attach --username='lvazquez-r3dh4t' --password='R3dh4t.2022.01'
            #sudo insights-client --register
            #  sudo yum localinstall http://satellite.opendemoday.com/pub/katello-ca-consumer-latest.noarch.rpm
            #  sudo subscription-manager register --org redhat --username admin --password r3dh4t1!
            SHELL
        end
    end 

end
