---
- name: Setup terminal
  hosts: localhost

  tasks:

    - name: Download multiple files into an specific directory
      ansible.builtin.get_url:
        url: https://github.com/romkatv/powerlevel10k-media/raw/master/{{ item }}
        dest: /home/lvazquez/Downloads/{{ item }}
        mode: '0755'
        owner: lvazquez
        group: lvazquez
      loop:
        - MesloLGS%20NF%20Regular.ttf
        - MesloLGS%20NF%20Bold.ttf
        - MesloLGS%20NF%20Italic.ttf
        - MesloLGS%20NF%20Bold%20Italic.ttf

    - name: Debug message "change font in terminal"
      ansible.builtin.debug:
        msg: "{{ 'Remeber to change the font in the terminal' }}"
    